# Use Dockerized infrastructure
sudo: false
language: python
before_install:
- mkdir -p lib
install:
- pip install -r requirements.txt -t lib/
script:
- echo "No Script to run"
# [START travis_deploy]
deploy:
    provider: gae
    skip_cleanup: true
    keyfile: client-secret.json
    project: spell-bot
    default: true
# [END travis_deploy]